# Generated by Django 4.1.1 on 2022-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('UserId', models.CharField(max_length=20)),
                ('FollowUserId', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('postid', models.CharField(max_length=20)),
                ('likeduserid', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('I', 'Image'), ('V', 'Video')], max_length=10)),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
    ]
