# Generated by Django 4.1.1 on 2022-10-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_posts_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='likeduserid',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='postlikes',
            constraint=models.UniqueConstraint(fields=('postid', 'likeduserid'), name='unique_like_key'),
        ),
    ]
